output: main.o my_print.o
	gcc -m32 -o output main.cpp my_print.o -lstdc++

my_print.o: my_print.asm
	nasm -f elf -o my_print.o my_print.asm

main.o: main.cpp
	gcc -m32 -c main.cpp

clean:
	rm *.o output
	